export const REQUEST_QUESTION = "REQUEST_QUESTION";
export const REQUEST_QUESTIONS = "REQUEST_QUESTIONS";
export const REQUEST_SAVE_QUESTION = "REQUEST_SAVE_QUESTION";
export const REQUEST_SAVE_QUESTION_ANSWER = "REQUEST_SAVE_QUESTION_ANSWER";
export const RECEIVE_QUESTION = "RECEIVE_QUESTION";
export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS";
export const RECEIVE_SAVE_QUESTION = "RECEIVE_SAVE_QUESTION";
export const RECEIVE_SAVE_QUESTION_ANSWER = "RECEIVE_SAVE_QUESTION_ANSWER";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const REQUEST_ME = "REQUEST_ME";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const RECEIVE_LOGOUT = "RECEIVE_LOGOUT";
export const RECEIVE_ME = "RECEIVE_ME";

export const REQUEST_USER = "REQUEST_USER";
export const REQUEST_USERS = "REQUEST_USERS";
export const RECEIVE_USER = "RECEIVE_USER";
export const RECEIVE_USERS = "RECEIVE_USERS";
